#############################################################################
# Generated by PAGE version 4.14
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Adobe Arabic} -size 24 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font10
vTcl:font:add_font \
    "-family {Adobe Arabic} -size 30 -weight normal -slant roman -underline 1 -overstrike 0" \
    user \
    vTcl:font14
vTcl:font:add_font \
    "-family {Adobe Arabic} -size 40 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font16
vTcl:font:add_font \
    "-family {Adobe Arabic} -size 48 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font9
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top37
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.fra38
    set site_4_0 $site_3_0.fra39
    set site_4_0 $site_3_0.fra49
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#333333} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1427x774+0+24
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1440 775
    wm minsize $top 72 15
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra38 \
        -borderwidth 2 -relief groove -background {#009999} -height 755 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 1405 
    vTcl:DefineAlias "$top.fra38" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra38
    label $site_3_0.lab39 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#009999} -font $::vTcl(fonts,vTcl:font9,object) \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Washing Bot} 
    vTcl:DefineAlias "$site_3_0.lab39" "Label1" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra40 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 535 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 635 
    vTcl:DefineAlias "$site_3_0.fra40" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab41 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#009999} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Face Detection} 
    vTcl:DefineAlias "$site_3_0.lab41" "Label2" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu42 \
        -command Btn_Start -takefocus 0 -text Start -compound center 
    vTcl:DefineAlias "$site_3_0.tBu42" "TButton1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu43 \
        -command Btn_TakePhoto -takefocus {} -text {Take Photo} 
    vTcl:DefineAlias "$site_3_0.tBu43" "TButton2" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu44 \
        -command Btn_Detect -takefocus {} -text Detect 
    vTcl:DefineAlias "$site_3_0.tBu44" "TButton3" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra39 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 205 \
        -width 685 
    vTcl:DefineAlias "$site_3_0.fra39" "Frame3" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra39
    label $site_4_0.lab40 \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font14,object) \
        -foreground {#000000} -text {User Information} 
    vTcl:DefineAlias "$site_4_0.lab40" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab41 \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#000000} -text {Acc No. :   } 
    vTcl:DefineAlias "$site_4_0.lab41" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab42 \
        -anchor w -background {#d9d9d9} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#000000} \
        -text WB_00001 
    vTcl:DefineAlias "$site_4_0.lab42" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab43 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {User Name :} 
    vTcl:DefineAlias "$site_4_0.lab43" "Label4_1" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Bill Amount : } 
    vTcl:DefineAlias "$site_4_0.lab44" "Label4_2" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Last Time Use : } 
    vTcl:DefineAlias "$site_4_0.lab45" "Label4_3" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab46 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {U Thar Htet San} 
    vTcl:DefineAlias "$site_4_0.lab46" "Label5_4" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab47 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 80000-Kyats 
    vTcl:DefineAlias "$site_4_0.lab47" "Label5_5" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab40 \
        -in $site_4_0 -x 10 -y 10 -width 174 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab41 \
        -in $site_4_0 -x 21 -y 48 -width 137 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab42 \
        -in $site_4_0 -x 170 -y 50 -width 458 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab43 \
        -in $site_4_0 -x 20 -y 82 -width 137 -height 24 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab44 \
        -in $site_4_0 -x 20 -y 120 -width 137 -height 24 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab45 \
        -in $site_4_0 -x 20 -y 160 -width 137 -height 24 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab46 \
        -in $site_4_0 -x 170 -y 87 -width 458 -height 24 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab47 \
        -in $site_4_0 -x 170 -y 120 -width 458 -height 24 -anchor nw \
        -bordermode ignore 
    label $site_3_0.lab48 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {"Mon Jun 11 22:21:37 2018"} 
    vTcl:DefineAlias "$site_3_0.lab48" "Label5_6" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra49 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 155 \
        -width 695 
    vTcl:DefineAlias "$site_3_0.fra49" "Frame4" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra49
    label $site_4_0.lab51 \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#000000} -text {Wash Type : } 
    vTcl:DefineAlias "$site_4_0.lab51" "Label6" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab52 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#d9d9d9} -compound left \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Normal 
    vTcl:DefineAlias "$site_4_0.lab52" "Label6_8" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab53 \
        -activebackground {#f9f9f9} -activeforeground black -anchor e \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Cost : } 
    vTcl:DefineAlias "$site_4_0.lab53" "Label6_9" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab54 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {8000 - Kyats} 
    vTcl:DefineAlias "$site_4_0.lab54" "Label6_10" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Long Time : } 
    vTcl:DefineAlias "$site_4_0.lab55" "Label6_11" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab56 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {30 min} 
    vTcl:DefineAlias "$site_4_0.lab56" "Label6_12" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab58 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Time :} 
    vTcl:DefineAlias "$site_4_0.lab58" "Label6_14" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab60 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Will Finish At : } 
    vTcl:DefineAlias "$site_4_0.lab60" "Label6_11" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab61 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text { 22:41:37} 
    vTcl:DefineAlias "$site_4_0.lab61" "Label6_10" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab51 \
        -in $site_4_0 -x 30 -y 40 -anchor nw -bordermode ignore 
    place $site_4_0.lab52 \
        -in $site_4_0 -x 140 -y 40 -width 101 -height 34 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab53 \
        -in $site_4_0 -x 400 -y 40 -width 101 -height 34 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab54 \
        -in $site_4_0 -x 520 -y 40 -width 131 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab55 \
        -in $site_4_0 -x 30 -y 70 -width 101 -height 34 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab56 \
        -in $site_4_0 -x 141 -y 70 -width 101 -height 34 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab58 \
        -in $site_4_0 -x 330 -y -290 -width 101 -height 34 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab60 \
        -in $site_4_0 -x 20 -y 110 -width 131 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab61 \
        -in $site_4_0 -x 160 -y 110 -width 301 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    label $site_3_0.lab50 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font14,object) \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Wash Status} 
    vTcl:DefineAlias "$site_3_0.lab50" "Label2_7" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab57 \
        -activebackground {#f9f} -activeforeground black \
        -background {#009999} -font $::vTcl(fonts,vTcl:font16,object) \
        -foreground {#000066} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Date - ( Mon Jun 11 22:21:37 2018 )} 
    vTcl:DefineAlias "$site_3_0.lab57" "Label6_13" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu62 \
        -command Btn_Normal -takefocus 0 -text Normal -compound center 
    vTcl:DefineAlias "$site_3_0.tBu62" "TButton1_11" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu63 \
        -command Btn_Quick -takefocus 0 -text Quick -compound center 
    vTcl:DefineAlias "$site_3_0.tBu63" "TButton1_12" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu64 \
        -command Btn_Wool -takefocus 0 -text Wool -compound center 
    vTcl:DefineAlias "$site_3_0.tBu64" "TButton1_13" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu65 \
        -command Btn_HaveyDuty -takefocus 0 -text {Heavy Duty} \
        -compound center 
    vTcl:DefineAlias "$site_3_0.tBu65" "TButton1_14" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu74 \
        -command Btn_StartWash -takefocus {} -text {Start Wash} 
    vTcl:DefineAlias "$site_3_0.tBu74" "TButton3_22" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab39 \
        -in $site_3_0 -x 600 -y 10 -anchor nw -bordermode ignore 
    place $site_3_0.fra40 \
        -in $site_3_0 -x 30 -y 100 -width 635 -relwidth 0 -height 535 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab41 \
        -in $site_3_0 -x 270 -y 60 -anchor nw -bordermode ignore 
    place $site_3_0.tBu42 \
        -in $site_3_0 -x 30 -y 650 -width 187 -relwidth 0 -height 94 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu43 \
        -in $site_3_0 -x 247 -y 650 -width 197 -relwidth 0 -height 94 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu44 \
        -in $site_3_0 -x 474 -y 650 -width 187 -relwidth 0 -height 94 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra39 \
        -in $site_3_0 -x 690 -y 100 -width 685 -relwidth 0 -height 205 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 860 -y 260 -width 458 -height 24 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra49 \
        -in $site_3_0 -x 690 -y 340 -width 695 -relwidth 0 -height 155 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 700 -y 350 -width 113 -height 34 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 940 -y 60 -width 431 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu62 \
        -in $site_3_0 -x 690 -y 520 -width 167 -relwidth 0 -height 94 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu63 \
        -in $site_3_0 -x 870 -y 520 -width 167 -relwidth 0 -height 94 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu64 \
        -in $site_3_0 -x 1060 -y 520 -width 157 -relwidth 0 -height 94 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu65 \
        -in $site_3_0 -x 1230 -y 520 -width 157 -relwidth 0 -height 94 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu74 \
        -in $site_3_0 -x 700 -y 640 -width 677 -relwidth 0 -height 94 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra38 \
        -in $top -x 10 -y 10 -width 1405 -relwidth 0 -height 755 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

