#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Jun 20, 2018 12:50:14 AM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import wb_ui_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = New_Toplevel (root)
    wb_ui_support.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = New_Toplevel (w)

    wb_ui_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel():
    global w
    w.destroy()
    w = None


class New_Toplevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85'
        font10 = "-family {Adobe Arabic} -size 24 -weight normal "  \
            "-slant roman -underline 0 -overstrike 0"
        font14 = "-family {Adobe Arabic} -size 30 -weight normal "  \
            "-slant roman -underline 1 -overstrike 0"
        font16 = "-family {Adobe Arabic} -size 40 -weight normal "  \
            "-slant roman -underline 0 -overstrike 0"
        font9 = "-family {Adobe Arabic} -size 48 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1427x774+0+24")
        top.title("New Toplevel")
        top.configure(background="#333333")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.01, rely=0.01, relheight=0.98, relwidth=0.98)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#009999")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")
        self.Frame1.configure(width=1405)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.43, rely=0.01, height=60, width=199)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#009999")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Washing Bot''')

        self.Frame2 = Frame(self.Frame1)
        self.Frame2.place(relx=0.02, rely=0.13, relheight=0.71, relwidth=0.45)
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(background="#d9d9d9")
        self.Frame2.configure(highlightbackground="#d9d9d9")
        self.Frame2.configure(highlightcolor="black")
        self.Frame2.configure(width=635)

        self.Label2 = Label(self.Frame1)
        self.Label2.place(relx=0.19, rely=0.08, height=34, width=113)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#009999")
        self.Label2.configure(font=font10)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Face Detection''')

        '''image '''
        self.ImageView = ttk.Label(self.Frame2)
        self.ImageView.place(relx=0, rely=0, relheight=1, relwidth=1)

        self.TButton1 = ttk.Button(self.Frame1)
        self.TButton1.place(relx=0.02, rely=0.86, height=94, width=187)
        self.TButton1.configure(command=wb_ui_support.Btn_Start)
        self.TButton1.configure(takefocus="0")
        self.TButton1.configure(text='''Start''')
        self.TButton1.configure(compound="center")

        self.TButton2 = ttk.Button(self.Frame1)
        self.TButton2.place(relx=0.17, rely=0.86, height=94, width=197)
        self.TButton2.configure(command=wb_ui_support.Btn_TakePhoto)
        self.TButton2.configure(takefocus="")
        self.TButton2.configure(text='''Take Photo''')

        self.TButton3 = ttk.Button(self.Frame1)
        self.TButton3.place(relx=0.33, rely=0.86, height=94, width=187)
        self.TButton3.configure(command=wb_ui_support.Btn_Detect)
        self.TButton3.configure(takefocus="")
        self.TButton3.configure(text='''Detect''')

        self.Frame3 = Frame(self.Frame1)
        self.Frame3.place(relx=0.49, rely=0.13, relheight=0.27, relwidth=0.49)
        self.Frame3.configure(relief=GROOVE)
        self.Frame3.configure(borderwidth="2")
        self.Frame3.configure(relief=GROOVE)
        self.Frame3.configure(background="#d9d9d9")
        self.Frame3.configure(width=685)

        self.Label3 = Label(self.Frame3)
        self.Label3.place(relx=0.01, rely=0.05, height=30, width=174)
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(font=font14)
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''User Information''')
        self.Label3.configure(width=174)

        self.Label4 = Label(self.Frame3)
        self.Label4.place(relx=0.03, rely=0.23, height=24, width=137)
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(font=font10)
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(text='''Acc No. :''')
        self.Label4.configure(width=137)

        self.Label5 = Label(self.Frame3)
        self.Label5.place(relx=0.25, rely=0.24, height=24, width=458)
        self.Label5.configure(anchor=W)
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(font=font10)
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(text='''WB_00001''')
        self.Label5.configure(width=458)

        self.Label4_1 = Label(self.Frame3)
        self.Label4_1.place(relx=0.03, rely=0.4, height=24, width=137)
        self.Label4_1.configure(activebackground="#f9f9f9")
        self.Label4_1.configure(activeforeground="black")
        self.Label4_1.configure(background="#d9d9d9")
        self.Label4_1.configure(font=font10)
        self.Label4_1.configure(foreground="#000000")
        self.Label4_1.configure(highlightbackground="#d9d9d9")
        self.Label4_1.configure(highlightcolor="black")
        self.Label4_1.configure(text='''User Name :''')

        self.Label4_2 = Label(self.Frame3)
        self.Label4_2.place(relx=0.03, rely=0.59, height=24, width=137)
        self.Label4_2.configure(activebackground="#f9f9f9")
        self.Label4_2.configure(activeforeground="black")
        self.Label4_2.configure(background="#d9d9d9")
        self.Label4_2.configure(font=font10)
        self.Label4_2.configure(foreground="#000000")
        self.Label4_2.configure(highlightbackground="#d9d9d9")
        self.Label4_2.configure(highlightcolor="black")
        self.Label4_2.configure(text='''Bill Amount :''')

        self.Label4_3 = Label(self.Frame3)
        self.Label4_3.place(relx=0.03, rely=0.78, height=24, width=137)
        self.Label4_3.configure(activebackground="#f9f9f9")
        self.Label4_3.configure(activeforeground="black")
        self.Label4_3.configure(background="#d9d9d9")
        self.Label4_3.configure(font=font10)
        self.Label4_3.configure(foreground="#000000")
        self.Label4_3.configure(highlightbackground="#d9d9d9")
        self.Label4_3.configure(highlightcolor="black")
        self.Label4_3.configure(text='''Last Time Use :''')

        self.Label5_4 = Label(self.Frame3)
        self.Label5_4.place(relx=0.25, rely=0.42, height=24, width=458)
        self.Label5_4.configure(activebackground="#f9f9f9")
        self.Label5_4.configure(activeforeground="black")
        self.Label5_4.configure(anchor=W)
        self.Label5_4.configure(background="#d9d9d9")
        self.Label5_4.configure(font=font10)
        self.Label5_4.configure(foreground="#000000")
        self.Label5_4.configure(highlightbackground="#d9d9d9")
        self.Label5_4.configure(highlightcolor="black")
        self.Label5_4.configure(text='''U Thar Htet San''')

        self.Label5_5 = Label(self.Frame3)
        self.Label5_5.place(relx=0.25, rely=0.59, height=24, width=458)
        self.Label5_5.configure(activebackground="#f9f9f9")
        self.Label5_5.configure(activeforeground="black")
        self.Label5_5.configure(anchor=W)
        self.Label5_5.configure(background="#d9d9d9")
        self.Label5_5.configure(font=font10)
        self.Label5_5.configure(foreground="#000000")
        self.Label5_5.configure(highlightbackground="#d9d9d9")
        self.Label5_5.configure(highlightcolor="black")
        self.Label5_5.configure(text='''80000-Kyats''')

        self.Label5_6 = Label(self.Frame1)
        self.Label5_6.place(relx=0.61, rely=0.34, height=24, width=458)
        self.Label5_6.configure(activebackground="#f9f9f9")
        self.Label5_6.configure(activeforeground="black")
        self.Label5_6.configure(anchor=W)
        self.Label5_6.configure(background="#d9d9d9")
        self.Label5_6.configure(font=font10)
        self.Label5_6.configure(foreground="#000000")
        self.Label5_6.configure(highlightbackground="#d9d9d9")
        self.Label5_6.configure(highlightcolor="black")
        self.Label5_6.configure(text='''"Mon Jun 11 22:21:37 2018"''')

        self.Frame4 = Frame(self.Frame1)
        self.Frame4.place(relx=0.49, rely=0.45, relheight=0.21, relwidth=0.49)
        self.Frame4.configure(relief=GROOVE)
        self.Frame4.configure(borderwidth="2")
        self.Frame4.configure(relief=GROOVE)
        self.Frame4.configure(background="#d9d9d9")
        self.Frame4.configure(width=695)

        self.Label6 = Label(self.Frame4)
        self.Label6.place(relx=0.04, rely=0.26, height=34, width=101)
        self.Label6.configure(background="#d9d9d9")
        self.Label6.configure(font=font10)
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(text='''Wash Type :''')

        self.Label6_8 = Label(self.Frame4)
        self.Label6_8.place(relx=0.2, rely=0.26, height=34, width=101)
        self.Label6_8.configure(activebackground="#f9f9f9")
        self.Label6_8.configure(activeforeground="black")
        self.Label6_8.configure(anchor=W)
        self.Label6_8.configure(background="#d9d9d9")
        self.Label6_8.configure(compound="left")
        self.Label6_8.configure(font=font10)
        self.Label6_8.configure(foreground="#000000")
        self.Label6_8.configure(highlightbackground="#d9d9d9")
        self.Label6_8.configure(highlightcolor="black")
        self.Label6_8.configure(text='''Normal''')

        self.Label6_9 = Label(self.Frame4)
        self.Label6_9.place(relx=0.58, rely=0.26, height=34, width=101)
        self.Label6_9.configure(activebackground="#f9f9f9")
        self.Label6_9.configure(activeforeground="black")
        self.Label6_9.configure(anchor=E)
        self.Label6_9.configure(background="#d9d9d9")
        self.Label6_9.configure(font=font10)
        self.Label6_9.configure(foreground="#000000")
        self.Label6_9.configure(highlightbackground="#d9d9d9")
        self.Label6_9.configure(highlightcolor="black")
        self.Label6_9.configure(text='''Cost :''')

        self.Label6_10 = Label(self.Frame4)
        self.Label6_10.place(relx=0.75, rely=0.26, height=34, width=131)
        self.Label6_10.configure(activebackground="#f9f9f9")
        self.Label6_10.configure(activeforeground="black")
        self.Label6_10.configure(anchor=W)
        self.Label6_10.configure(background="#d9d9d9")
        self.Label6_10.configure(font=font10)
        self.Label6_10.configure(foreground="#000000")
        self.Label6_10.configure(highlightbackground="#d9d9d9")
        self.Label6_10.configure(highlightcolor="black")
        self.Label6_10.configure(text='''8000 - Kyats''')
        self.Label6_10.configure(width=131)

        self.Label6_11 = Label(self.Frame4)
        self.Label6_11.place(relx=0.04, rely=0.45, height=34, width=101)
        self.Label6_11.configure(activebackground="#f9f9f9")
        self.Label6_11.configure(activeforeground="black")
        self.Label6_11.configure(background="#d9d9d9")
        self.Label6_11.configure(font=font10)
        self.Label6_11.configure(foreground="#000000")
        self.Label6_11.configure(highlightbackground="#d9d9d9")
        self.Label6_11.configure(highlightcolor="black")
        self.Label6_11.configure(text='''Long Time :''')

        self.Label6_12 = Label(self.Frame4)
        self.Label6_12.place(relx=0.2, rely=0.45, height=34, width=101)
        self.Label6_12.configure(activebackground="#f9f9f9")
        self.Label6_12.configure(activeforeground="black")
        self.Label6_12.configure(anchor=W)
        self.Label6_12.configure(background="#d9d9d9")
        self.Label6_12.configure(font=font10)
        self.Label6_12.configure(foreground="#000000")
        self.Label6_12.configure(highlightbackground="#d9d9d9")
        self.Label6_12.configure(highlightcolor="black")
        self.Label6_12.configure(text='''30 min''')

        self.Label6_14 = Label(self.Frame4)
        self.Label6_14.place(relx=0.47, rely=-1.87, height=34, width=101)
        self.Label6_14.configure(activebackground="#f9f9f9")
        self.Label6_14.configure(activeforeground="black")
        self.Label6_14.configure(background="#d9d9d9")
        self.Label6_14.configure(font=font10)
        self.Label6_14.configure(foreground="#000000")
        self.Label6_14.configure(highlightbackground="#d9d9d9")
        self.Label6_14.configure(highlightcolor="black")
        self.Label6_14.configure(text='''Time :''')

        self.Label6_11 = Label(self.Frame4)
        self.Label6_11.place(relx=0.03, rely=0.71, height=34, width=131)
        self.Label6_11.configure(activebackground="#f9f9f9")
        self.Label6_11.configure(activeforeground="black")
        self.Label6_11.configure(background="#d9d9d9")
        self.Label6_11.configure(font=font10)
        self.Label6_11.configure(foreground="#000000")
        self.Label6_11.configure(highlightbackground="#d9d9d9")
        self.Label6_11.configure(highlightcolor="black")
        self.Label6_11.configure(text='''Will Finish At :''')
        self.Label6_11.configure(width=131)

        self.Label6_10 = Label(self.Frame4)
        self.Label6_10.place(relx=0.23, rely=0.71, height=34, width=301)
        self.Label6_10.configure(activebackground="#f9f9f9")
        self.Label6_10.configure(activeforeground="black")
        self.Label6_10.configure(anchor=W)
        self.Label6_10.configure(background="#d9d9d9")
        self.Label6_10.configure(font=font10)
        self.Label6_10.configure(foreground="#000000")
        self.Label6_10.configure(highlightbackground="#d9d9d9")
        self.Label6_10.configure(highlightcolor="black")
        self.Label6_10.configure(text='''22:41:37''')
        self.Label6_10.configure(width=301)

        self.Label2_7 = Label(self.Frame1)
        self.Label2_7.place(relx=0.5, rely=0.46, height=34, width=113)
        self.Label2_7.configure(activebackground="#f9f9f9")
        self.Label2_7.configure(activeforeground="black")
        self.Label2_7.configure(background="#d9d9d9")
        self.Label2_7.configure(font=font14)
        self.Label2_7.configure(foreground="#000000")
        self.Label2_7.configure(highlightbackground="#d9d9d9")
        self.Label2_7.configure(highlightcolor="black")
        self.Label2_7.configure(text='''Wash Status''')

        self.Label6_13 = Label(self.Frame1)
        self.Label6_13.place(relx=0.67, rely=0.08, height=34, width=431)
        self.Label6_13.configure(activebackground="#f9f")
        self.Label6_13.configure(activeforeground="black")
        self.Label6_13.configure(background="#009999")
        self.Label6_13.configure(font=font16)
        self.Label6_13.configure(foreground="#000066")
        self.Label6_13.configure(highlightbackground="#d9d9d9")
        self.Label6_13.configure(highlightcolor="black")
        self.Label6_13.configure(text='''Date - ( Mon Jun 11 22:21:37 2018 )''')
        self.Label6_13.configure(width=431)

        self.TButton1_11 = ttk.Button(self.Frame1)
        self.TButton1_11.place(relx=0.49, rely=0.69, height=94, width=167)
        self.TButton1_11.configure(command=wb_ui_support.Btn_Normal)
        self.TButton1_11.configure(takefocus="0")
        self.TButton1_11.configure(text='''Normal''')
        self.TButton1_11.configure(width=167)
        self.TButton1_11.configure(compound="center")

        self.TButton1_12 = ttk.Button(self.Frame1)
        self.TButton1_12.place(relx=0.62, rely=0.69, height=94, width=167)
        self.TButton1_12.configure(command=wb_ui_support.Btn_Quick)
        self.TButton1_12.configure(takefocus="0")
        self.TButton1_12.configure(text='''Quick''')
        self.TButton1_12.configure(width=167)
        self.TButton1_12.configure(compound="center")

        self.TButton1_13 = ttk.Button(self.Frame1)
        self.TButton1_13.place(relx=0.75, rely=0.69, height=94, width=157)
        self.TButton1_13.configure(command=wb_ui_support.Btn_Wool)
        self.TButton1_13.configure(takefocus="0")
        self.TButton1_13.configure(text='''Wool''')
        self.TButton1_13.configure(width=157)
        self.TButton1_13.configure(compound="center")

        self.TButton1_14 = ttk.Button(self.Frame1)
        self.TButton1_14.place(relx=0.88, rely=0.69, height=94, width=157)
        self.TButton1_14.configure(command=wb_ui_support.Btn_HaveyDuty)
        self.TButton1_14.configure(takefocus="0")
        self.TButton1_14.configure(text='''Heavy Duty''')
        self.TButton1_14.configure(width=157)
        self.TButton1_14.configure(compound="center")

        self.TButton3_22 = ttk.Button(self.Frame1)
        self.TButton3_22.place(relx=0.5, rely=0.85, height=94, width=677)
        self.TButton3_22.configure(command=wb_ui_support.Btn_StartWash)
        self.TButton3_22.configure(takefocus="")
        self.TButton3_22.configure(text='''Start Wash''')
        self.TButton3_22.configure(width=677)



if __name__ == '__main__':
    vp_start_gui()


#
# def StartCamear():
    # cv_capture = cv2.VideoCapture()
    # cv_capture.open(0)  # have to use whatever your camera id actually is
    # root = tk.Tk()
    # setattr(root, 'quit_flag', False)
    # def set_quit_flag():
    #     root.quit_flag = True
    # root.protocol('WM_DELETE_WINDOW', set_quit_flag)  # avoid errors on exit
    # image_label = tk.Label(master=root)  # the video will go here
    # image_label.pack()
    # root.after(0, func=lambda: update_all(root, imageLabel, cv_capture))
    # root.mainloop()
